// Static help center content - seeded into Supabase on first admin visit
// or used as fallback when articles haven't been seeded yet

export interface HelpCategory {
  name: string;
  slug: string;
  icon: string;
  description: string;
  sortOrder: number;
}

export interface HelpArticle {
  title: string;
  slug: string;
  categorySlug: string;
  role: string;
  tags: string[];
  isFeatured: boolean;
  readTimeMinutes: number;
  content: string;
}

export const HELP_CATEGORIES: HelpCategory[] = [
  { name: 'Getting Started', slug: 'getting-started', icon: '🚛', description: 'Setup guides and first steps', sortOrder: 1 },
  { name: 'IFTA Filing', slug: 'ifta-filing', icon: '📋', description: 'How to file, calculate, and submit', sortOrder: 2 },
  { name: 'BOL Scanning', slug: 'bol-scanning', icon: '📷', description: 'Camera setup and scanning tips', sortOrder: 3 },
  { name: 'Mileage Tracking', slug: 'mileage-tracking', icon: '📍', description: 'GPS and manual entry guides', sortOrder: 4 },
  { name: 'Fleet Management', slug: 'fleet-management', icon: '🚛', description: 'Managing drivers and trucks', sortOrder: 5 },
  { name: 'Billing & Plans', slug: 'billing-plans', icon: '💰', description: 'Subscriptions, payments, and invoices', sortOrder: 6 },
  { name: 'App Setup', slug: 'app-setup', icon: '📱', description: 'Install PWA, notifications, and settings', sortOrder: 7 },
  { name: 'Account & Profile', slug: 'account-profile', icon: '🔐', description: 'Settings, security, and data privacy', sortOrder: 8 },
];

export const HELP_ARTICLES: HelpArticle[] = [
  // Getting Started
  { title: 'Welcome to TrueTrucker — Start Here', slug: 'welcome-start-here', categorySlug: 'getting-started', role: 'all', tags: ['welcome', 'intro', 'start'], isFeatured: true, readTimeMinutes: 3, content: `# Welcome to TrueTrucker IFTA Pro!\n\nTrueTrucker is the easiest way to track your mileage, manage fuel receipts, and file your IFTA reports — all from your phone.\n\n## What You Can Do\n\n- **Track Mileage** — Automatically or manually log miles by state\n- **Scan Receipts** — Use your camera to capture fuel receipts\n- **File IFTA Reports** — Auto-generated quarterly reports\n- **Manage Your Fleet** — Invite drivers, assign trucks, track performance\n- **Scan BOLs** — Digitize Bills of Lading with your camera\n\n## Getting Started\n\n1. Complete your driver profile\n2. Add your truck details\n3. Start your first trip\n4. Scan your first fuel receipt\n\nThat's it! TrueTrucker handles the IFTA calculations for you.` },
  { title: 'How to complete your driver profile', slug: 'complete-driver-profile', categorySlug: 'getting-started', role: 'all', tags: ['profile', 'setup', 'driver'], isFeatured: false, readTimeMinutes: 2, content: `# How to Complete Your Driver Profile\n\n1. Go to **Account** from the bottom navigation\n2. Fill in your personal information\n3. Add your company details and DOT number\n4. Enter your FEID number\n5. Click **Save**\n\nYour profile information is used to auto-fill IFTA reports and ensure compliance.` },
  { title: 'How to set up your truck details', slug: 'setup-truck-details', categorySlug: 'getting-started', role: 'all', tags: ['truck', 'vehicle', 'setup'], isFeatured: false, readTimeMinutes: 2, content: `# How to Set Up Your Truck\n\n1. Navigate to **Vehicles** from the dashboard\n2. Tap **Add New Truck**\n3. Enter your truck number, make, model, and year\n4. Add your VIN and license plate\n5. Select your fuel type\n6. Save your truck\n\nYour truck details are linked to trips and IFTA reports for accurate filing.` },
  { title: 'How to join a fleet with invite code', slug: 'join-fleet-invite-code', categorySlug: 'getting-started', role: 'driver', tags: ['fleet', 'invite', 'join', 'code'], isFeatured: true, readTimeMinutes: 2, content: `# How to Join a Fleet\n\nYour fleet owner will give you a 6-character invite code.\n\n1. During onboarding, select **I Drive for a Fleet**\n2. Enter the invite code (e.g., MIKE42)\n3. The app will confirm the fleet name\n4. Select your assigned truck\n5. Tap **Confirm & Continue**\n\nOnce joined, your fleet owner can view your trips, BOLs, and IFTA data.` },
  { title: 'How to set up GPS mileage tracking', slug: 'setup-gps-tracking', categorySlug: 'getting-started', role: 'all', tags: ['gps', 'tracking', 'location', 'mileage'], isFeatured: true, readTimeMinutes: 3, content: `# Setting Up GPS Mileage Tracking\n\n## Enable GPS\n1. Go to your phone settings\n2. Find TrueTrucker in app permissions\n3. Allow location access "While using the app"\n\n## Start Tracking\n1. Open TrueTrucker\n2. Tap the **Auto Track** toggle on your dashboard\n3. Your miles are now being tracked automatically\n\n## Important Notes\n- GPS only tracks when you start a trip\n- Battery usage is minimal\n- You can switch to manual entry anytime\n- All data is private and encrypted` },
  { title: 'How to install the app on your phone', slug: 'install-app-phone', categorySlug: 'getting-started', role: 'all', tags: ['install', 'pwa', 'phone', 'app'], isFeatured: false, readTimeMinutes: 2, content: `# Install TrueTrucker on Your Phone\n\n## Android\n1. Open Chrome and go to the app\n2. Tap the three dots menu (⋮)\n3. Tap "Add to Home Screen"\n4. Tap "Install"\n\n## iPhone\n1. Open Safari and go to the app\n2. Tap the Share button\n3. Scroll down to "Add to Home Screen"\n4. Tap "Add"\n\nThe app icon will appear on your home screen just like a regular app!` },
  { title: 'Understanding your dashboard', slug: 'understanding-dashboard', categorySlug: 'getting-started', role: 'all', tags: ['dashboard', 'overview', 'home'], isFeatured: false, readTimeMinutes: 3, content: `# Your Dashboard\n\nYour dashboard is your IFTA command center. Here's what you'll see:\n\n- **Quick Stats** — Total miles, fuel purchases, tax owed, active reports\n- **Monthly Chart** — Visual trend of miles and fuel costs\n- **Quick Actions** — Start trip, scan receipt, view reports\n- **Auto Track Toggle** — Enable/disable GPS tracking\n\nAll data updates in real-time as you drive and log fuel purchases.` },
  { title: 'How to start your first trip', slug: 'start-first-trip', categorySlug: 'getting-started', role: 'all', tags: ['trip', 'first', 'start'], isFeatured: false, readTimeMinutes: 2, content: `# Starting Your First Trip\n\n1. Go to **Trips** from the dashboard\n2. Tap **New Trip**\n3. Enter origin city and state\n4. Enter destination city and state\n5. Select your truck\n6. Tap **Start Trip**\n\nIf GPS tracking is enabled, miles will be logged automatically by state.` },
  { title: 'How to log your first fuel receipt', slug: 'log-first-fuel-receipt', categorySlug: 'getting-started', role: 'all', tags: ['receipt', 'fuel', 'scan', 'first'], isFeatured: false, readTimeMinutes: 2, content: `# Logging Your First Fuel Receipt\n\n1. Tap **Scan Receipt** from the dashboard\n2. Point your camera at the receipt\n3. The app reads the total, gallons, and price\n4. Verify the extracted data\n5. Select the state where you fueled\n6. Tap **Save Receipt**\n\nReceipts are used in IFTA calculations to determine tax credits per state.` },
  { title: 'How to scan your first BOL', slug: 'scan-first-bol', categorySlug: 'getting-started', role: 'all', tags: ['bol', 'scan', 'first', 'bill of lading'], isFeatured: false, readTimeMinutes: 3, content: `# Scanning Your First Bill of Lading\n\n1. Tap **Scan** from the bottom navigation\n2. Allow camera access when prompted\n3. Point your camera at the BOL document\n4. Hold steady until the scan completes\n5. Review the captured information\n6. Tap **Save BOL**\n\n## Tips\n- Use good lighting\n- Keep the document flat\n- Fill the camera frame with the document` },
  { title: 'Setting up notifications', slug: 'setting-up-notifications', categorySlug: 'getting-started', role: 'all', tags: ['notifications', 'alerts', 'setup'], isFeatured: false, readTimeMinutes: 2, content: `# Setting Up Notifications\n\n1. When prompted, tap **Allow Notifications**\n2. You'll receive alerts for:\n   - IFTA filing deadlines\n   - Report status updates\n   - Messages from fleet owner\n   - Auto-save confirmations\n\nYou can customize notification settings in your Account page.` },
  { title: 'Completing your first IFTA report', slug: 'complete-first-ifta-report', categorySlug: 'getting-started', role: 'all', tags: ['ifta', 'report', 'first', 'file'], isFeatured: false, readTimeMinutes: 4, content: `# Your First IFTA Report\n\nTrueTrucker auto-generates your IFTA report at the end of each quarter.\n\n1. Go to **IFTA Reports**\n2. Select the current quarter\n3. Review your miles by state\n4. Review fuel purchases by state\n5. Check the calculated tax owed\n6. Tap **Submit Report**\n\nThe app calculates everything for you based on your trips and fuel receipts.` },

  // IFTA Filing
  { title: 'What is IFTA and who needs to file', slug: 'what-is-ifta', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'basics', 'requirements'], isFeatured: false, readTimeMinutes: 4, content: `# What is IFTA?\n\nThe International Fuel Tax Agreement (IFTA) is a tax collection agreement between the 48 contiguous US states and 10 Canadian provinces.\n\n## Who Needs to File?\n\nYou need an IFTA license if your vehicle:\n- Has two axles and weighs over 26,000 lbs, OR\n- Has three or more axles regardless of weight, OR\n- Is used in combination and the combined weight exceeds 26,000 lbs\n\nAND you travel in two or more IFTA jurisdictions.\n\n## Filing Schedule\n- Q1 (Jan-Mar): Due April 30\n- Q2 (Apr-Jun): Due July 31\n- Q3 (Jul-Sep): Due October 31\n- Q4 (Oct-Dec): Due January 31` },
  { title: 'IFTA filing deadlines by quarter', slug: 'ifta-deadlines', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'deadline', 'quarter', 'due date'], isFeatured: false, readTimeMinutes: 2, content: `# IFTA Filing Deadlines\n\n| Quarter | Period | Deadline |\n|---------|--------|----------|\n| Q1 | January - March | April 30 |\n| Q2 | April - June | July 31 |\n| Q3 | July - September | October 31 |\n| Q4 | October - December | January 31 |\n\n**Important:** Late filings incur penalties. TrueTrucker sends reminders at 30, 14, 7, and 1 day before each deadline.` },
  { title: 'How IFTA tax is calculated', slug: 'how-ifta-calculated', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'tax', 'calculation', 'formula'], isFeatured: true, readTimeMinutes: 5, content: `# How IFTA Tax is Calculated\n\n## Step 1: Calculate Fleet MPG\nTotal Miles ÷ Total Gallons = Fleet MPG\n\n## Step 2: Fuel Used Per State\nMiles in State ÷ Fleet MPG = Gallons Used\n\n## Step 3: Tax Per State\n(Gallons Used - Gallons Purchased) × Tax Rate = Tax Owed\n\n## Example\n- Total miles: 38,492 | Total gallons: 6,842\n- Fleet MPG: 5.63\n- Florida: 8,421 miles ÷ 5.63 = 1,496 gal used\n- Purchased in FL: 1,200 gal\n- FL tax rate: $0.334/gal\n- Tax owed: (1,496 - 1,200) × $0.334 = $98.86\n\nIf you purchased MORE fuel than used in a state, you get a **credit**.` },
  { title: 'How to submit your IFTA report', slug: 'submit-ifta-report', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'submit', 'file', 'report'], isFeatured: true, readTimeMinutes: 3, content: `# Submitting Your IFTA Report\n\n1. Go to **IFTA Reports**\n2. Select the quarter to file\n3. Review the auto-calculated summary\n4. Verify miles and fuel by state\n5. Tap **Submit Report**\n6. Confirm the submission\n7. Download your PDF confirmation\n\nYou'll receive a confirmation number after submission.` },
  { title: 'How to download your IFTA PDF', slug: 'download-ifta-pdf', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'pdf', 'download', 'print'], isFeatured: false, readTimeMinutes: 2, content: `# Downloading Your IFTA Report PDF\n\n1. Go to **IFTA Reports**\n2. Find the report you want\n3. Tap **Download PDF**\n4. The PDF includes:\n   - Cover page with your info\n   - Summary of miles and fuel\n   - State-by-state breakdown\n   - Supporting document list\n\nPDFs are formatted to official IFTA standards and ready to file.` },
  { title: 'Understanding IFTA tax credits', slug: 'ifta-tax-credits', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'credit', 'tax', 'refund'], isFeatured: false, readTimeMinutes: 3, content: `# Understanding IFTA Tax Credits\n\nYou receive a credit when you purchase **more fuel** in a state than you actually used there.\n\n## How Credits Work\n- Miles driven in Texas: 3,847\n- Fuel used: 683 gallons (based on fleet MPG)\n- Fuel purchased in Texas: 750 gallons\n- Excess: 67 gallons × $0.20 = **$13.40 credit**\n\nCredits offset taxes owed in other states, reducing your total tax bill.` },
  { title: 'State by state IFTA tax rates', slug: 'state-ifta-tax-rates', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'tax', 'rates', 'state'], isFeatured: false, readTimeMinutes: 3, content: `# IFTA Tax Rates by State\n\nIFTA tax rates vary by state and are updated quarterly. TrueTrucker automatically uses the current rates.\n\nSome example rates (diesel):\n- Florida: $0.334/gal\n- Georgia: $0.312/gal\n- Texas: $0.200/gal\n- Ohio: $0.280/gal\n- Tennessee: $0.274/gal\n- California: $0.421/gal\n\n**Note:** Rates change quarterly. TrueTrucker updates rates automatically.` },
  { title: 'IFTA penalties and how to avoid them', slug: 'ifta-penalties', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'penalties', 'late', 'fine'], isFeatured: false, readTimeMinutes: 3, content: `# IFTA Penalties\n\n## Late Filing\n- $50 penalty or 10% of tax due (whichever is greater)\n- Interest accrues monthly on unpaid tax\n\n## How to Avoid Penalties\n1. Set up notifications for deadline reminders\n2. Review your auto-generated report early\n3. Submit at least 3 days before the deadline\n4. Keep all fuel receipts organized\n\nTrueTrucker sends reminders at 30, 14, 7, and 1 day before deadlines.` },
  { title: 'Frequently asked IFTA questions', slug: 'ifta-faq', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'faq', 'questions'], isFeatured: false, readTimeMinutes: 5, content: `# IFTA FAQ\n\n**Q: Do I need to file if I only drove in one state?**\nA: No. IFTA only applies if you travel in two or more jurisdictions.\n\n**Q: What if I have no activity for a quarter?**\nA: You still need to file a "zero" report.\n\n**Q: Can I amend a filed report?**\nA: Yes. Use the "Request Amendment" button on submitted reports.\n\n**Q: How long should I keep records?**\nA: Keep all IFTA records for at least 4 years.` },
  // More IFTA articles (shorter stubs)
  { title: 'Understanding miles by state', slug: 'understanding-miles-by-state', categorySlug: 'ifta-filing', role: 'all', tags: ['miles', 'state', 'breakdown'], isFeatured: false, readTimeMinutes: 3, content: `# Understanding Miles by State\n\nIFTA requires you to report miles driven in each state. TrueTrucker tracks this automatically using GPS or your manual entries.\n\nWhen you start a trip crossing state lines, the app calculates mileage per state using route data.\n\nYou can view and edit your miles by state breakdown in the IFTA Reports section.` },
  { title: 'How to read your IFTA summary', slug: 'read-ifta-summary', categorySlug: 'ifta-filing', role: 'all', tags: ['ifta', 'summary', 'read'], isFeatured: false, readTimeMinutes: 3, content: `# Reading Your IFTA Summary\n\nYour IFTA summary shows:\n- **Total Miles** — All miles driven this quarter\n- **Taxable Miles** — Miles subject to IFTA tax\n- **Total Gallons** — All fuel purchased\n- **Fleet MPG** — Your fuel efficiency\n- **Net Tax Owed** — Total tax due after credits` },
  { title: 'How to send report to accountant', slug: 'send-report-accountant', categorySlug: 'ifta-filing', role: 'all', tags: ['accountant', 'email', 'send', 'report'], isFeatured: false, readTimeMinutes: 2, content: `# Sending Reports to Your Accountant\n\n1. Open your IFTA report\n2. Tap **Download PDF**\n3. Share the PDF via email\n\nThe PDF includes all the information your accountant needs for IFTA filing.` },
  { title: 'What happens after you file', slug: 'after-you-file', categorySlug: 'ifta-filing', role: 'all', tags: ['file', 'submit', 'after', 'status'], isFeatured: false, readTimeMinutes: 2, content: `# After You File\n\nOnce submitted, your report status changes to "Submitted." You'll receive:\n- A confirmation number\n- A downloadable PDF receipt\n- Email confirmation\n\nYour report will be reviewed by your base jurisdiction.` },
  { title: 'How to file an amended report', slug: 'file-amended-report', categorySlug: 'ifta-filing', role: 'all', tags: ['amend', 'correct', 'fix', 'report'], isFeatured: false, readTimeMinutes: 3, content: `# Filing an Amended Report\n\n1. Find the submitted report in IFTA Reports\n2. Tap **Request Amendment**\n3. Explain what needs to change\n4. Submit for review\n5. If approved, a new report is generated\n\nThe original report is marked as amended with a full audit trail.` },
  { title: 'IFTA filing for fleet owners', slug: 'ifta-filing-fleet-owners', categorySlug: 'ifta-filing', role: 'fleet_owner', tags: ['ifta', 'fleet', 'owner', 'combined'], isFeatured: false, readTimeMinutes: 4, content: `# Fleet IFTA Filing\n\nAs a fleet owner, you can:\n- View individual driver reports\n- Generate a combined fleet report\n- Submit all reports at once\n- Download individual or combined PDFs\n\nGo to IFTA Reports and select the fleet view to see all driver reports.` },
  { title: 'How to generate a combined fleet report', slug: 'combined-fleet-report', categorySlug: 'ifta-filing', role: 'fleet_owner', tags: ['fleet', 'combined', 'report'], isFeatured: false, readTimeMinutes: 3, content: `# Combined Fleet Reports\n\n1. Go to IFTA Reports\n2. Select the quarter\n3. View fleet totals at the top\n4. Each driver's contribution is listed\n5. Download the combined PDF\n\nThe combined report includes all trucks and drivers in your fleet.` },
  { title: 'What documents do I need to file', slug: 'documents-needed-file', categorySlug: 'ifta-filing', role: 'all', tags: ['documents', 'file', 'requirements'], isFeatured: false, readTimeMinutes: 2, content: `# Required Documents for IFTA Filing\n\n- Mileage logs (by state)\n- Fuel receipts (showing gallons and location)\n- Vehicle information\n- IFTA license number\n\nTrueTrucker stores all of this for you and includes it in your generated report.` },
  { title: 'How to handle rejected reports', slug: 'handle-rejected-reports', categorySlug: 'ifta-filing', role: 'all', tags: ['rejected', 'report', 'fix'], isFeatured: false, readTimeMinutes: 3, content: `# Handling Rejected Reports\n\nIf a report is rejected:\n1. Check the rejection reason in your notifications\n2. Fix the identified issues\n3. Regenerate the report\n4. Resubmit before the deadline\n\nCommon rejection reasons: missing receipts, incorrect mileage, missing state data.` },

  // BOL Scanning
  { title: 'How to scan a Bill of Lading', slug: 'how-to-scan-bol', categorySlug: 'bol-scanning', role: 'all', tags: ['bol', 'scan', 'camera', 'bill of lading'], isFeatured: true, readTimeMinutes: 3, content: `# How to Scan a Bill of Lading\n\n## Before You Start\n- Camera permission must be enabled\n- Good lighting available\n- BOL document flat and readable\n\n## Steps\n1. Tap the **Scan** button\n2. Point camera at the BOL\n3. Hold steady until captured\n4. Review the scan\n5. Tap **Save**\n\n## Tips\n- Use natural light\n- Keep document flat\n- Fill the frame\n- Hold steady for 2 seconds` },
  { title: 'Camera setup on Android', slug: 'camera-setup-android', categorySlug: 'bol-scanning', role: 'all', tags: ['camera', 'android', 'setup', 'permission'], isFeatured: false, readTimeMinutes: 2, content: `# Camera Setup — Android\n\n1. Open **Settings** on your phone\n2. Go to **Apps** → **TrueTrucker**\n3. Tap **Permissions**\n4. Enable **Camera**\n5. Return to TrueTrucker and try scanning\n\nIf still not working, try clearing the app cache.` },
  { title: 'Camera setup on iPhone', slug: 'camera-setup-iphone', categorySlug: 'bol-scanning', role: 'all', tags: ['camera', 'iphone', 'ios', 'setup'], isFeatured: false, readTimeMinutes: 2, content: `# Camera Setup — iPhone\n\n1. Open **Settings**\n2. Scroll to **TrueTrucker**\n3. Enable **Camera** toggle\n4. Return to TrueTrucker\n\nNote: On iOS, you must use Safari to install the PWA for full camera access.` },
  { title: 'Tips for better scan quality', slug: 'better-scan-quality', categorySlug: 'bol-scanning', role: 'all', tags: ['scan', 'quality', 'tips', 'bol'], isFeatured: false, readTimeMinutes: 2, content: `# Tips for Better Scans\n\n1. **Good lighting** — Natural light works best\n2. **Flat surface** — Place document on a flat surface\n3. **Fill the frame** — Get close enough to fill the screen\n4. **Hold steady** — Wait 2 seconds before capturing\n5. **Clean lens** — Wipe your camera lens\n6. **Avoid shadows** — Position to avoid casting shadows` },
  { title: 'How to retake a bad scan', slug: 'retake-bad-scan', categorySlug: 'bol-scanning', role: 'all', tags: ['retake', 'scan', 'redo'], isFeatured: false, readTimeMinutes: 1, content: `# Retaking a Bad Scan\n\n1. After scanning, review the image\n2. If blurry or incomplete, tap **Retake**\n3. Adjust lighting and position\n4. Scan again\n\nYou can retake as many times as needed before saving.` },
  { title: 'How to attach BOL to a report', slug: 'attach-bol-report', categorySlug: 'bol-scanning', role: 'all', tags: ['bol', 'attach', 'report', 'trip'], isFeatured: false, readTimeMinutes: 2, content: `# Attaching BOL to a Report\n\nScanned BOLs are automatically linked to your active trip. To manually attach:\n\n1. Go to **BOL Management**\n2. Find the BOL\n3. Tap **Edit**\n4. Select the trip to attach it to\n5. Save` },
  { title: 'How to find a previously scanned BOL', slug: 'find-previous-bol', categorySlug: 'bol-scanning', role: 'all', tags: ['bol', 'find', 'history', 'previous'], isFeatured: false, readTimeMinutes: 1, content: `# Finding Previous BOLs\n\n1. Go to **BOL Management**\n2. Use the search bar to find by BOL number\n3. Or filter by date, shipper, or status\n\nAll scanned BOLs are saved permanently in your account.` },
  { title: 'Troubleshooting camera issues', slug: 'troubleshoot-camera', categorySlug: 'bol-scanning', role: 'all', tags: ['camera', 'troubleshoot', 'fix', 'problem'], isFeatured: false, readTimeMinutes: 3, content: `# Troubleshooting Camera Issues\n\n**Camera not opening:**\n- Check permissions in phone settings\n- Restart the app\n- Clear browser cache\n\n**Image blurry:**\n- Clean camera lens\n- Use better lighting\n- Hold more steady\n\n**BOL not saving:**\n- Check internet connection\n- Try offline mode\n- Contact support if persistent` },

  // Mileage Tracking
  { title: 'How GPS mileage tracking works', slug: 'how-gps-tracking-works', categorySlug: 'mileage-tracking', role: 'all', tags: ['gps', 'tracking', 'how', 'works'], isFeatured: false, readTimeMinutes: 3, content: `# How GPS Tracking Works\n\nWhen enabled, TrueTrucker uses your phone's GPS to track your location during trips.\n\n## How It Works\n1. Start a trip from the dashboard\n2. GPS tracks your position periodically\n3. State border crossings are detected automatically\n4. Miles are calculated and logged per state\n5. Stop the trip when you arrive\n\n## Privacy\n- Location is only tracked during active trips\n- Data is encrypted and private\n- You control when tracking starts and stops` },
  { title: 'How to start and stop a trip', slug: 'start-stop-trip', categorySlug: 'mileage-tracking', role: 'all', tags: ['trip', 'start', 'stop', 'tracking'], isFeatured: false, readTimeMinutes: 2, content: `# Starting and Stopping Trips\n\n## Start a Trip\n1. Toggle **Auto Track** on the dashboard, or\n2. Go to **Trips** → **New Trip** for manual entry\n\n## Stop a Trip\n1. Toggle **Auto Track** off, or\n2. Go to **Trips** and tap **End Trip**\n\nAll miles are saved automatically.` },
  { title: 'How to enter miles manually', slug: 'enter-miles-manually', categorySlug: 'mileage-tracking', role: 'all', tags: ['manual', 'entry', 'miles', 'odometer'], isFeatured: false, readTimeMinutes: 2, content: `# Manual Mileage Entry\n\n1. Go to **Trips** → **New Trip**\n2. Enter origin and destination\n3. Enter total miles driven\n4. Add miles per state crossed\n5. Save the trip\n\nManual entries are included in your IFTA calculations just like GPS-tracked trips.` },
  { title: 'How to edit a mileage entry', slug: 'edit-mileage-entry', categorySlug: 'mileage-tracking', role: 'all', tags: ['edit', 'mileage', 'correct', 'fix'], isFeatured: false, readTimeMinutes: 2, content: `# Editing Mileage\n\n1. Go to **Trips**\n2. Find the trip to edit\n3. Tap on it to open details\n4. Make your changes\n5. Save\n\nEdited entries are reflected in your IFTA calculations immediately.` },
  { title: 'How to fix incorrect mileage', slug: 'fix-incorrect-mileage', categorySlug: 'mileage-tracking', role: 'all', tags: ['fix', 'incorrect', 'mileage', 'error'], isFeatured: false, readTimeMinutes: 2, content: `# Fixing Incorrect Mileage\n\nIf GPS logged incorrect miles:\n1. Open the trip in **Trips**\n2. Tap **Edit**\n3. Adjust the total miles and per-state breakdown\n4. Save changes\n\nChanges are reflected in your next IFTA report.` },
  { title: 'Mileage tracking battery tips', slug: 'mileage-battery-tips', categorySlug: 'mileage-tracking', role: 'all', tags: ['battery', 'gps', 'power', 'tips'], isFeatured: false, readTimeMinutes: 2, content: `# Battery Tips for GPS Tracking\n\n- Keep your phone plugged in while driving\n- Close unused apps\n- GPS tracking uses about 5-10% battery per hour\n- Use a car charger for long trips\n- Enable battery saver mode on long hauls` },
  { title: 'What happens if GPS loses signal', slug: 'gps-loses-signal', categorySlug: 'mileage-tracking', role: 'all', tags: ['gps', 'signal', 'lost', 'offline'], isFeatured: false, readTimeMinutes: 2, content: `# GPS Signal Loss\n\nIf GPS signal is lost during a trip:\n- The app continues tracking from the last known position\n- When signal returns, it resumes automatically\n- You can manually add miles for the gap\n- Consider manual entry for areas with poor coverage` },
  { title: 'How to export your mileage log', slug: 'export-mileage-log', categorySlug: 'mileage-tracking', role: 'all', tags: ['export', 'mileage', 'csv', 'download'], isFeatured: false, readTimeMinutes: 2, content: `# Exporting Your Mileage Log\n\n1. Go to **Analytics**\n2. Select the date range\n3. Tap **Export to CSV**\n4. The file downloads to your device\n\nExported data includes dates, miles, states, and trip details.` },
  { title: 'Mileage tracking FAQ', slug: 'mileage-faq', categorySlug: 'mileage-tracking', role: 'all', tags: ['mileage', 'faq', 'questions'], isFeatured: false, readTimeMinutes: 3, content: `# Mileage Tracking FAQ\n\n**Q: Can I use both GPS and manual entry?**\nA: Yes! You can mix methods as needed.\n\n**Q: Does tracking work in Canada?**\nA: Yes, GPS works across North America.\n\n**Q: How accurate is GPS tracking?**\nA: Within 1-2% of actual miles driven.` },

  // Fleet Management
  { title: 'How to set up your fleet', slug: 'setup-fleet', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['fleet', 'setup', 'create'], isFeatured: false, readTimeMinutes: 3, content: `# Setting Up Your Fleet\n\n1. Sign up as a fleet owner\n2. Enter your company name\n3. Add your first truck\n4. Get your fleet invite code\n5. Share the code with drivers\n\nYour fleet dashboard shows all drivers, trucks, and reports in one place.` },
  { title: 'How to get your fleet invite code', slug: 'get-fleet-invite-code', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['fleet', 'invite', 'code', 'share'], isFeatured: false, readTimeMinutes: 1, content: `# Your Fleet Invite Code\n\nYour unique invite code is shown on your Fleet Dashboard. Share it with drivers so they can join your fleet.\n\nExample code: MIKE42\n\nTap **Copy Code** to copy it to your clipboard.` },
  { title: 'How to invite drivers to your fleet', slug: 'invite-drivers-fleet', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['invite', 'driver', 'fleet', 'add'], isFeatured: false, readTimeMinutes: 2, content: `# Inviting Drivers\n\n1. Copy your fleet invite code\n2. Share it with your driver via text, email, or in person\n3. The driver enters the code during signup or onboarding\n4. They're automatically added to your fleet\n\nYou can also send the install link with the code to all drivers from the Fleet Dashboard.` },
  { title: 'How to add a truck to your fleet', slug: 'add-truck-fleet', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['truck', 'add', 'fleet', 'vehicle'], isFeatured: false, readTimeMinutes: 2, content: `# Adding Trucks\n\n1. Go to **Vehicles**\n2. Tap **Add New Truck**\n3. Enter truck number, make, model, year\n4. Add VIN and license plate\n5. Save\n\nTrucks can be assigned to drivers in the Fleet Dashboard.` },
  { title: 'How to assign drivers to trucks', slug: 'assign-drivers-trucks', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['assign', 'driver', 'truck'], isFeatured: false, readTimeMinutes: 2, content: `# Assigning Drivers to Trucks\n\n1. Go to your **Fleet Dashboard**\n2. Find the driver\n3. Tap **Assign Truck**\n4. Select the truck number\n5. Confirm\n\nDrivers can only be assigned to one truck at a time.` },
  { title: 'How to view driver activity', slug: 'view-driver-activity', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['driver', 'activity', 'view', 'monitor'], isFeatured: false, readTimeMinutes: 2, content: `# Viewing Driver Activity\n\nFrom your Fleet Dashboard:\n- See each driver's total miles\n- View their fuel purchases\n- Check their IFTA report status\n- Review their BOL submissions\n\nTap any driver's name for detailed analytics.` },
  { title: 'How to deactivate a driver', slug: 'deactivate-driver', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['deactivate', 'driver', 'remove'], isFeatured: false, readTimeMinutes: 2, content: `# Deactivating a Driver\n\n1. Go to **Fleet Dashboard**\n2. Find the driver\n3. Tap **Deactivate**\n4. Confirm\n\nDeactivated drivers can no longer submit data under your fleet. Their historical data is preserved.` },
  { title: 'How to remove a driver from fleet', slug: 'remove-driver-fleet', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['remove', 'driver', 'fleet'], isFeatured: false, readTimeMinutes: 2, content: `# Removing a Driver\n\n1. Go to **Fleet Dashboard**\n2. Find the driver\n3. Tap **Remove from Fleet**\n4. Confirm\n\nRemoving a driver is permanent. They would need a new invite code to rejoin.` },
  { title: 'How to message your drivers', slug: 'message-drivers', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['message', 'chat', 'driver', 'communication'], isFeatured: false, readTimeMinutes: 2, content: `# Messaging Drivers\n\n1. Go to **Messages**\n2. Select a driver or send to all\n3. Type your message\n4. Tap **Send**\n\nDrivers receive a notification when you send a message.` },
  { title: 'Understanding fleet analytics', slug: 'fleet-analytics', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['fleet', 'analytics', 'reports'], isFeatured: false, readTimeMinutes: 3, content: `# Fleet Analytics\n\nYour Analytics page shows:\n- Total fleet miles and fuel costs\n- Per-driver performance comparison\n- Fuel efficiency rankings\n- IFTA tax summary across all drivers\n- State-by-state mileage breakdown\n\nUse filters to compare quarters and track trends.` },
  { title: 'How to access driver BOLs', slug: 'access-driver-bols', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['bol', 'driver', 'access', 'view'], isFeatured: false, readTimeMinutes: 1, content: `# Accessing Driver BOLs\n\nAs a fleet owner, you can view all BOLs submitted by your drivers.\n\n1. Go to **BOL Management**\n2. All fleet driver BOLs are visible\n3. Filter by driver, date, or status` },
  { title: 'How to generate fleet IFTA reports', slug: 'generate-fleet-ifta', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['fleet', 'ifta', 'report', 'generate'], isFeatured: false, readTimeMinutes: 3, content: `# Fleet IFTA Reports\n\n1. Go to **IFTA Reports**\n2. Select the quarter\n3. View the combined fleet summary\n4. Each driver's contribution is listed\n5. Download individual or combined reports\n6. Submit all at once or individually` },
  { title: 'Fleet owner billing and plans', slug: 'fleet-billing-plans', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['billing', 'fleet', 'plan', 'pricing'], isFeatured: false, readTimeMinutes: 2, content: `# Fleet Billing\n\nFleet plans are based on the number of trucks:\n- Fleet plans include all driver accounts\n- Billing is monthly or annual\n- Manage your plan from **Account** → **Billing**` },
  { title: 'Fleet management FAQ', slug: 'fleet-faq', categorySlug: 'fleet-management', role: 'fleet_owner', tags: ['fleet', 'faq', 'questions'], isFeatured: false, readTimeMinutes: 3, content: `# Fleet Management FAQ\n\n**Q: Can a driver be in multiple fleets?**\nA: No, each driver can only be in one fleet at a time.\n\n**Q: Can I see driver locations in real-time?**\nA: You can see trip status but not live GPS position.\n\n**Q: How many drivers can I have?**\nA: There's no limit on your fleet plan.` },

  // Billing
  { title: 'Understanding our pricing plans', slug: 'pricing-plans', categorySlug: 'billing-plans', role: 'all', tags: ['pricing', 'plans', 'cost', 'subscription'], isFeatured: false, readTimeMinutes: 3, content: `# Pricing Plans\n\nVisit the **Pricing** page for current plan details.\n\nAll plans include:\n- Unlimited mileage tracking\n- BOL scanning\n- IFTA report generation\n- Mobile app access\n\nFleet plans add multi-driver management and combined reporting.` },
  { title: 'How to upgrade your plan', slug: 'upgrade-plan', categorySlug: 'billing-plans', role: 'all', tags: ['upgrade', 'plan', 'billing'], isFeatured: false, readTimeMinutes: 2, content: `# Upgrading Your Plan\n\n1. Go to **Account**\n2. Tap **Manage Subscription**\n3. Select a new plan\n4. Confirm payment\n\nUpgrades take effect immediately.` },
  { title: 'How to cancel your subscription', slug: 'cancel-subscription', categorySlug: 'billing-plans', role: 'all', tags: ['cancel', 'subscription', 'stop'], isFeatured: false, readTimeMinutes: 2, content: `# Canceling Your Subscription\n\n1. Go to **Account**\n2. Tap **Manage Subscription**\n3. Select **Cancel**\n4. Confirm\n\nYou'll retain access until the end of your current billing period.` },
  { title: 'How to update payment method', slug: 'update-payment-method', categorySlug: 'billing-plans', role: 'all', tags: ['payment', 'card', 'update', 'billing'], isFeatured: false, readTimeMinutes: 1, content: `# Updating Payment\n\n1. Go to **Account**\n2. Tap **Manage Subscription**\n3. Update your card information\n4. Save` },
  { title: 'How to download invoices', slug: 'download-invoices', categorySlug: 'billing-plans', role: 'all', tags: ['invoice', 'download', 'receipt', 'billing'], isFeatured: false, readTimeMinutes: 1, content: `# Downloading Invoices\n\n1. Go to **Invoices**\n2. Find the invoice you need\n3. Tap **Download**\n\nAll past invoices are available for download.` },
  { title: 'What happens when trial expires', slug: 'trial-expires', categorySlug: 'billing-plans', role: 'all', tags: ['trial', 'expire', 'free', 'end'], isFeatured: false, readTimeMinutes: 2, content: `# When Your Trial Expires\n\nAfter your 7-day free trial:\n- You'll need to select a paid plan\n- Your data is preserved\n- Upgrade anytime to continue using the app\n\nWe send reminders before your trial ends.` },
  { title: 'Refund policy', slug: 'refund-policy-help', categorySlug: 'billing-plans', role: 'all', tags: ['refund', 'money back', 'policy'], isFeatured: false, readTimeMinutes: 2, content: `# Refund Policy\n\nPlease see our full [Refund Policy](/refund-policy) page for details.\n\nIn general, we offer refunds within 30 days of purchase for unused services.` },
  { title: 'How to downgrade your plan', slug: 'downgrade-plan', categorySlug: 'billing-plans', role: 'all', tags: ['downgrade', 'plan', 'change'], isFeatured: false, readTimeMinutes: 2, content: `# Downgrading Your Plan\n\n1. Go to **Account** → **Manage Subscription**\n2. Select a lower tier plan\n3. Changes take effect at the next billing cycle\n\nYour data is preserved when downgrading.` },
  { title: 'Billing FAQ', slug: 'billing-faq', categorySlug: 'billing-plans', role: 'all', tags: ['billing', 'faq', 'questions', 'payment'], isFeatured: false, readTimeMinutes: 3, content: `# Billing FAQ\n\n**Q: Can I get a receipt for each payment?**\nA: Yes, invoices are automatically generated.\n\n**Q: Do you offer annual billing?**\nA: Yes, with a discount. See the Pricing page.\n\n**Q: What payment methods do you accept?**\nA: All major credit and debit cards via Stripe.` },

  // App Setup
  { title: 'How to install on Android', slug: 'install-android', categorySlug: 'app-setup', role: 'all', tags: ['install', 'android', 'pwa'], isFeatured: false, readTimeMinutes: 2, content: `# Installing on Android\n\n1. Open Chrome browser\n2. Go to the TrueTrucker website\n3. Tap the three dots menu (⋮)\n4. Tap "Add to Home Screen"\n5. Tap "Install"\n\nThe TrueTrucker icon appears on your home screen!` },
  { title: 'How to install on iPhone', slug: 'install-iphone', categorySlug: 'app-setup', role: 'all', tags: ['install', 'iphone', 'ios', 'pwa'], isFeatured: false, readTimeMinutes: 2, content: `# Installing on iPhone\n\n1. Open Safari (must be Safari!)\n2. Go to the TrueTrucker website\n3. Tap the Share button\n4. Tap "Add to Home Screen"\n5. Tap "Add"\n\nNote: Only Safari supports PWA installation on iOS.` },
  { title: 'How to enable notifications', slug: 'enable-notifications', categorySlug: 'app-setup', role: 'all', tags: ['notifications', 'enable', 'alerts'], isFeatured: false, readTimeMinutes: 2, content: `# Enabling Notifications\n\nWhen prompted, tap **Allow** to receive:\n- IFTA deadline reminders\n- Report updates\n- Fleet messages\n- System alerts\n\nYou can manage notifications in your phone settings.` },
  { title: 'How to enable GPS permissions', slug: 'enable-gps-permissions', categorySlug: 'app-setup', role: 'all', tags: ['gps', 'location', 'permission', 'enable'], isFeatured: false, readTimeMinutes: 2, content: `# Enabling GPS\n\n## Android\nSettings → Apps → TrueTrucker → Permissions → Location → Allow while using app\n\n## iPhone\nSettings → TrueTrucker → Location → While Using the App` },
  { title: 'How to enable camera permissions', slug: 'enable-camera-permissions', categorySlug: 'app-setup', role: 'all', tags: ['camera', 'permission', 'enable'], isFeatured: false, readTimeMinutes: 1, content: `# Enabling Camera\n\n## Android\nSettings → Apps → TrueTrucker → Permissions → Camera → Allow\n\n## iPhone\nSettings → TrueTrucker → Camera → Toggle On` },
  { title: 'How to use offline mode', slug: 'use-offline-mode', categorySlug: 'app-setup', role: 'all', tags: ['offline', 'mode', 'no internet'], isFeatured: false, readTimeMinutes: 3, content: `# Offline Mode\n\nTrueTrucker works offline! You can:\n- View saved reports\n- Fill out forms (saved locally)\n- View cached mileage data\n- View downloaded BOLs\n\nWhen back online, everything syncs automatically.` },
  { title: 'How to sync data when back online', slug: 'sync-data-online', categorySlug: 'app-setup', role: 'all', tags: ['sync', 'online', 'data'], isFeatured: false, readTimeMinutes: 2, content: `# Syncing Data\n\nWhen you reconnect to the internet:\n1. The app detects the connection automatically\n2. Queued data syncs in the background\n3. You'll see a "✅ Synced" confirmation\n\nNo action needed — it's fully automatic!` },
  { title: 'App not loading troubleshooting', slug: 'app-not-loading', categorySlug: 'app-setup', role: 'all', tags: ['loading', 'troubleshoot', 'error', 'not working'], isFeatured: false, readTimeMinutes: 3, content: `# App Not Loading?\n\n1. **Check internet connection**\n2. **Clear browser cache** — Settings → Clear browsing data\n3. **Restart the app** — Close and reopen\n4. **Update browser** — Use latest Chrome or Safari\n5. **Reinstall** — Remove from home screen and reinstall\n\nIf still not working, contact support.` },
  { title: 'How to clear app cache', slug: 'clear-app-cache', categorySlug: 'app-setup', role: 'all', tags: ['cache', 'clear', 'reset'], isFeatured: false, readTimeMinutes: 2, content: `# Clearing App Cache\n\n## Android Chrome\nSettings → Apps → Chrome → Storage → Clear Cache\n\n## iPhone Safari\nSettings → Safari → Clear History and Website Data\n\nNote: You may need to log in again after clearing cache.` },
  { title: 'How to set quiet hours', slug: 'set-quiet-hours', categorySlug: 'app-setup', role: 'all', tags: ['quiet', 'hours', 'notifications', 'silence'], isFeatured: false, readTimeMinutes: 1, content: `# Setting Quiet Hours\n\nUse your phone's Do Not Disturb settings to silence TrueTrucker notifications during specific hours.\n\nUrgent IFTA deadline notifications will still appear when you open the app.` },
  { title: 'App setup FAQ', slug: 'app-setup-faq', categorySlug: 'app-setup', role: 'all', tags: ['app', 'setup', 'faq'], isFeatured: false, readTimeMinutes: 3, content: `# App Setup FAQ\n\n**Q: Which browsers are supported?**\nA: Chrome (Android) and Safari (iPhone) are recommended.\n\n**Q: Does the app use a lot of data?**\nA: No, TrueTrucker is very data-efficient.\n\n**Q: Can I use it on a tablet?**\nA: Yes, it works on any device with a modern browser.` },

  // Account & Profile
  { title: 'How to update your profile', slug: 'update-profile', categorySlug: 'account-profile', role: 'all', tags: ['profile', 'update', 'edit'], isFeatured: false, readTimeMinutes: 2, content: `# Updating Your Profile\n\n1. Go to **Account**\n2. Edit your information\n3. Tap **Save**\n\nKeep your profile up to date for accurate IFTA reports.` },
  { title: 'How to change your password', slug: 'change-password', categorySlug: 'account-profile', role: 'all', tags: ['password', 'change', 'security'], isFeatured: false, readTimeMinutes: 2, content: `# Changing Your Password\n\n1. Go to the login page\n2. Tap **Forgot Password**\n3. Enter your email\n4. Check your email for a reset link\n5. Set a new password\n\nUse a strong password with letters, numbers, and symbols.` },
  { title: 'How to update your email', slug: 'update-email', categorySlug: 'account-profile', role: 'all', tags: ['email', 'update', 'change'], isFeatured: false, readTimeMinutes: 2, content: `# Updating Your Email\n\nContact support to update your email address, as it's linked to your authentication account.` },
  { title: 'Understanding data privacy', slug: 'data-privacy', categorySlug: 'account-profile', role: 'all', tags: ['privacy', 'data', 'security'], isFeatured: false, readTimeMinutes: 3, content: `# Data Privacy\n\nYour data is:\n- Encrypted in transit and at rest\n- Never sold to third parties\n- Only accessible by you (and your fleet owner if applicable)\n- Stored securely on Supabase servers\n\nSee our full [Privacy Policy](/privacy-policy) for details.` },
  { title: 'How to export your data', slug: 'export-data', categorySlug: 'account-profile', role: 'all', tags: ['export', 'data', 'download', 'backup'], isFeatured: false, readTimeMinutes: 2, content: `# Exporting Your Data\n\n1. Go to **Analytics**\n2. Select the date range\n3. Tap **Export to CSV**\n\nYou can export mileage logs, fuel receipts, and IFTA reports.` },
  { title: 'How to delete your account', slug: 'delete-account', categorySlug: 'account-profile', role: 'all', tags: ['delete', 'account', 'remove'], isFeatured: false, readTimeMinutes: 2, content: `# Deleting Your Account\n\n1. Go to **Account**\n2. Scroll to **Delete Account**\n3. Confirm deletion\n\n⚠️ This permanently deletes all your data and cannot be undone.\n\nAlternatively, visit the [Delete Account](/delete-account) page.` },
  { title: 'Account security best practices', slug: 'account-security', categorySlug: 'account-profile', role: 'all', tags: ['security', 'password', 'safety', 'best practices'], isFeatured: false, readTimeMinutes: 3, content: `# Account Security\n\n1. Use a strong, unique password\n2. Don't share your login credentials\n3. Log out on shared devices\n4. Keep your email address current\n5. Review your account activity regularly\n\nIf you suspect unauthorized access, change your password immediately and contact support.` },
];
